version: '3'
services:
    zoneminder:
        container_name: zmdev
        image: hub.tris.vn/zmdev
        build: 
            context: .
            dockerfile: ./ubuntu/xenial/Dockerfile
        restart: unless-stopped
        ports:
            - 8089:80
        network_mode: "bridge"
        privileged: true
        shm_size: 512M
        environment:
            - TZ=Asia/Ho_Chi_Minh
        volumes:
            - ./zoneminder:/ZoneMinder