/*
* Copyright (c) 2017 Liming Shao <lmshao@163.com>
*/

#include "VideoEncoding.h"

//g++ -w main.cpp VideoEncoding.cpp -o main $(pkg-config --cflags --libs libavutil libavformat libavcodec)
int main()
{
    VideoEncoding videoEncoding;

    // Using the .yuv file generated by the VideoDecoder project 
    const char *inFile = "../output/Sample_1280x534_yuv420p.yuv";
    const char *outFile = "../output/Sample1.h264";

    videoEncoding.init();

    // Configure AVCodecContext parameters Manually
    videoEncoding.initCodecContext();

    videoEncoding.readFrameProc(inFile, outFile);

}