/*
 * Copyright (c) 2017 Liming Shao <lmshao@163.com>
 */

#include "AudioEncoding.h"

//g++ -w main.cpp AudioEncoding.cpp -o main $(pkg-config --cflags --libs libavutil libavformat libavcodec)
int main()
{
    AudioEncoding audioEncoding;

    // use the pcm file generated by decoding mp3 file as input
    const char *inFile = "../output/out_s16le.pcm";
    const char *outFile = "../output/Out.mp3";

    audioEncoding.init();

    // Configure AVCodecContext parameters Manually
    audioEncoding.initCodecContext();

    audioEncoding.readFrameProc(inFile, outFile);
}